stages:
  get_data:
    cmd: python Get_data.py
    deps:
    - get_data.py
    outs:
    - data.csv
  train:
    cmd: python train.py
    deps:
    - train.py
    - data.csv
    outs:
    - plot.png
    metrics:
    - metrics.txt:
        cache: false